export enum NotificationType {
  BILL_DUE = 'BILL_DUE',
  LOW_BALANCE_FOR_BILL = 'LOW_BALANCE_FOR_BILL',
  BUDGET_AT_RISK = 'BUDGET_AT_RISK',
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
  GOAL_BEHIND_SCHEDULE = 'GOAL_BEHIND_SCHEDULE',
  GOAL_ACHIEVED = 'GOAL_ACHIEVED',
  EXPORT_READY = 'EXPORT_READY',
}
